name: social_graphs_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - networkx=2.5
  - ipykernel
  - jupyter
  - numpy=1.19.2
  - pandas=1.1.3
  - scikit-learn
  - matplotlib
  - seaborn
  - bs4
  - tqdm
  - nltk
  - python-louvain
  - camelot-py
  - plotly
  - cufflinks-py
  - tweepy
  - pip
  - pip:
      - "--editable ."
      - svgpathtools
      - svgpath2mpl
      - fa2
      - powerlaw
      - wordcloud