name: social_graphs_project
dependencies:
  - python=3.7
  - networkx=2.5
  - ipykernel
  - jupyter
  - numpy = 1.19.2
  - pandas = 1.1.3
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - nltk
  - python-louvain
  - pip
  - pip:
      - "--editable ."
      - tweepy
      - fa2
      - powerlaw
      - wordcloud
